name: Update SS3 version in R package

on:
  workflow_call:

jobs:
  update-ss3-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Get the latest stock synthesis binaries
        run: |
         curl https://api.github.com/repos/nmfs-stock-synthesis/stock-synthesis/releases/latest | grep "browser_download_url" | grep -Eo 'https://[^\"]*' | xargs wget

      - name: Get the link to the latest release (including version number)
        id: get-link-to-release
        run: |
          link_to_release=$(curl https://api.github.com/repos/nmfs-stock-synthesis/stock-synthesis/releases/latest | grep "html_url" | grep 'releases' | grep -Eo 'https://[^\"]*')
          echo "::set-output name=link_to_release::${link_to_release}"

      - name: Bump version using sed
        run: |
          sed -r -i 's/(Version: ?[0-9]+\.)([0-9]+)(\.[0-9+])/echo "\1\$((\2+1))\3"/ge' DESCRIPTION

      - name: Move exes to the right location
        run: |
          mv ss_linux inst/bin/Linux64/ss
          mv ss_win.exe inst/bin/Windows64/ss.exe
          mv ss_osx inst/bin/MacOS/ss
          rm ss_opt_osx
          rm ss_opt_linux
          rm ss_opt_win.exe

      - name: Change permissions for mac and linux exes
        run: |
          chmod a+x inst/bin/Linux64/ss
          chmod a+x inst/bin/MacOS/ss

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: |
            Update ss3 binaries
            From ${{ steps.get-link-to-release.outputs.link_to_release }}
          branch: update-ss3
          title: 'Update ss3 binaries'
          body: |

           Auto-generated by [update-ss3-version.yml][1]. Binaries from ${{ steps.get-link-to-release.outputs.link_to_release }}.

            [1]: https://github.com/nmfs-stock-synthesis/workflows/tree/main/.github/workflows/update-ss3-version.yml
