#' Create a jittered version of a survey index based on biomass data
#'
#' This function is used to create an index of abundance sampled from the true
#' biomass. It takes the biomass from the Report.sso file using the \code{r4ss}
#' function and then splits it.
#'
#' @param operating_path_in Folder path to the operating model
#' @param assess_path_in Folder path to the assessment model
#' @param dat_file_in Name of the data file to read in
#' @param assess_path_out Folder path of the assessment model to write to.
#' @param dat_file_out Name of the data file to write to
#' @param start_surv Starting year survey index
#' @param end_surv Ending year survey index
#' @param freq_surv Frequency to return index values survey index
#' @param sd_obs_surv Standard deviation of the observation error survey index
#' @param start_fish Starting year fishery index
#' @param end_fish Ending year fishery index
#' @param freq_fish Frequency to return index values fishery index
#' @param sd_obs_fish Standard deviation of the observation error fishery index
#' @param make_plot Logical - make a plot of the biomass and index values?
#' @export
#' @author Cole Monnahan (modified by Kot)
#' @examples \notrun{
#' # Location of the R package code:
#' # (I can't get system.file() to bring over the package files with the
#' # correct permissions for SS_output() to work. Resorting to this in
#' # the meantime.)
#' f_op <- "~/Documents/github/ss3sim/inst/extdata/flatfish-operating"
#' f_as <- "~/Documents/github/ss3sim/inst/extdata/flatfish-assessment"
#' add_noise_to_index(f_op, f_as, "flatfish.dat", assess_path_out = ".",
#' dat_file_out = "flatfish-modified.dat", start_year = 1930,
#' end_year = 1981, 1, make_plot = TRUE)
#' }

#f_as <- system.file("extdata", "flatfish-assessment", package="ss3sim")
#f_op <- system.file("extdata", "flatfish-operating", package="ss3sim")

add_noise_to_index <- function(operating_path_in,  assess_path_in,
  dat_file_in, assess_path_out, dat_file_out, start_surv, end_surv,
  freq_surv=1, sd_obs_surv = 0.1, start_fish, end_fish, freq_fish=1,
  sd_obs_fish = .1, make_plot=FALSE){

  require(r4ss)

  ## Calculate which years to have the index values
  years.surveyindex <- seq(from=start_surv, to=end_surv, by=freq_surv)
  years.fisheryindex <- seq(from=start_fish, to=end_fish, by=freq_fish)
  
  ## Grab the biomass from the report file generated by the operating model; drop
  ## the first two rows since they aren't what we want
  ts <- SS_output(dir=operating_path_in, repfile="Report.sso",
    covar=F, verbose=FALSE, printstats=FALSE)$timeseries[-c(1,2),]
  bio_all <- ts$Bio_all
  yr <- ts$Yr
  bio.survey <- bio_all[yr %in% years.surveyindex] # biomass for years w/ survey
  bio.fishery <- bio_all[yr %in% years.fisheryindex] # biomass for years w/ survey

  if(length(bio.survey)==0 | length(bio.fishery)==0) 
    stop("Error: no matching years in either survey of fishery, index has length 0")

  index.survey <- bio.survey*exp(rnorm(n=length(bio.survey), mean=0, sd=sd_obs_surv)-sd_obs_surv^2/2)
  ifelse(length(bio.survey)!=0, index.survey.text <-
    paste(years.surveyindex, 1, 2, index.survey, sd_obs_surv),
    index.survey.text <- NULL)
  index.fishery <- bio.fishery*exp(rnorm(n=length(bio.fishery), mean=0, sd=sd_obs_fish)-sd_obs_fish^2/2)
  ifelse(length(bio.fishery)!=0, index.fishery.text <-
    paste(years.fisheryindex, 1, 1, index.fishery, sd_obs_fish),
    index.fishery.text <- NULL)

  ## Just for testing purposes. Create crude plots?
  if(make_plot){
    plot(yr, bio_all, ylim=c(0, max(index.survey, index.fishery)*1.1), type="l")
    points(years.surveyindex, index.survey, pch=16, col="red")
    points(years.fisheryindex, index.fishery, pch=16, col="blue")
  }

  ## Open the .dat file for the assessment model and find the right lines to
  ## overwrite
  dat.current <- readLines(paste0(assess_path_in,"/", dat_file_in))

  ## Write to file how many lines to read
  ind.N <- grep("#_N_cpue_and_surveyabundance_observations", x=dat.current)
  dat.current[ind.N] <- paste((length(years.surveyindex)+length(years.fisheryindex)),
    " #_N_cpue_and_surveyabundance_observations -- created by add_noise_to_index R function")
  ind.start <- grep("#_year seas index obs", x=dat.current)[1]
  ind.end <- grep("#_N_fleets_with_discard", x=dat.current)
  if(length(ind.end)==0) # different version:
    ind.end <- grep("#_N_discard_fleets", x=dat.current)
  if(length(ind.end)==0)
    stop("Couldn't locate where to print data in the .dat file.")
  dat.new <- c(dat.current[1:ind.start], index.survey.text, index.fishery.text,
    dat.current[ind.end:length(dat.current)])

  ## Write it back to file, possibly overwriting the original
  writeLines(text=dat.new, con=paste0(assess_path_out,"/", dat_file_out))
}

