#' Create a jittered version of a survey index based on biomass data
#' 
#' This function is used to create an index of abundance sampled from the true
#' biomass. It takes the biomass from the Report.sso file using the \code{r4ss}
#' function and then splits it.
#' 
#' @param operating_path_in Folder path to the operating model
#' @param assess_path_in Folder path to the assessment model
#' @param dat_filename_in Name of the data file to read in
#' @param assess_path_out Folder path of the assessment model to write
#' to.
#' @param dat_filename_out Name of the data file to write to
#' @param start_year Starting year
#' @param end_year Ending year
#' @param frequency Frequency to return index values
#' @param sd_obs Standard deviation of the observation error
#' @param make_plot Logical - make a plot of the biomass and index
#' values?
#' @export
#' @author Cole Monnahan
#' @examples \notrun{
#' # Location of the R package code: 
#' # (I can't get system.file() to bring over the package files with the
#' # correct permissions for SS_output() to work. Resorting to this in
#' # the meantime.)
#' f_op <- "~/Documents/github/ss3sim/inst/extdata/flatfish-operating"
#' f_as <- "~/Documents/github/ss3sim/inst/extdata/flatfish-assessment"
#' add_noise_to_index(f_op, f_as, "flatfish.dat", assess_path_out = ".",
#' dat_filename_out = "flatfish-modified.dat", start_year = 1930,
#' end_year = 1981, 1, make_plot = TRUE)
#' }

#f_as <- system.file("extdata", "flatfish-assessment", package="ss3sim")
#f_op <- system.file("extdata", "flatfish-operating", package="ss3sim")

add_noise_to_index <- function(operating_path_in,
  assess_path_in, dat_filename_in,
  assess_path_out, dat_filename_out, start_year,
  end_year, frequency=1, sd_obs = .1, make_plot=FALSE){

  require(r4ss)
  ## Calculate which years to have the index values
  years.survey <- seq(from=start_year, to=end_year, by=frequency)
  
  ## Grab the biomass from the report file generated by the operating model; drop
  ## the first two rows since they aren't what we want
  ts <- SS_output(dir=operating_path_in, repfile="Report.sso",
    covar=F, verbose=FALSE, printstats=FALSE)$timeseries[-c(1,2),]
  bio_all <- ts$Bio_all
  yr <- ts$Yr
  bio <- bio_all[yr %in% years.survey] # biomass for years w/ survey
  if(length(bio)==0) stop("Error: no matching years, index has length 0")
  index <- bio*exp(rnorm(n=length(bio), mean=0, sd=sd_obs)-sd_obs^2/2)
  index.text <- paste(years.survey, 1, 2, index, sd_obs)
  ## Just for testing purposes. Create crude plots?
  if(make_plot){
    plot(yr, bio_all, ylim=c(0, max(index)*1.1), type="l")
    points(years.survey, index, pch=16)
  }
  ## Open the .dat file for the assessment model and find the right lines to
  ## overwrite
  dat.current <- readLines(paste0(assess_path_in,"/", dat_filename_in))
  ## Write to file how many lines to read
  ind.N <- grep("#_N_cpue_and_surveyabundance_observations", x=dat.current)
  dat.current[ind.N] <- paste(length(years.survey),
    " #_N_cpue_and_surveyabundance_observations -- created by add_noise_to_index R function")
  ind.start <- grep("#_year seas index obs", x=dat.current)[1]
  ind.end <- grep("#_N_fleets_with_discard", x=dat.current)
  if(length(ind.end)==0) # different version:
    ind.end <- grep("#_N_discard_fleets", x=dat.current)
  if(length(ind.end)==0) 
    stop("Couldn't locate where to print data in the .dat file.")
  dat.new <- c(dat.current[1:ind.start], index.text,
    dat.current[ind.end:length(dat.current)])
  ## Write it back to file, possibly overwriting the original
  writeLines(text=dat.new, con=paste0(assess_path_out,"/", dat_filename_out))
}

