#' Determine if a Stock Synthesis run was successful
#'
#' Use the presence of files generated by Stock Synthesis to determine if the
#' run was successful or not. There are two levels of success that must
#' be determined if the run was meant to include estimating the hessian.
#'
#' @param dir A character string specifying the path to the folder with the
#' results from the run of the Stock Synthesis model.
#'
#' @return A named vector with two values, `ran` and `hess`,
#' (1) a zero or one for the presence of the `Report.sso` file and
#' (2) a zero or one for the presence of a positive definite hessian matrix.
#' @author Kelli Faye Johnson
#'
get_success <- function(dir) {
  outvec <- c("ran" = 0, "hess" = 0)
  if (file.exists(file.path(dir, "Report.sso"))) {
    outvec["ran"] <- 1
  } else {
    return(outvec)
  }
  cor_file_in <- dir(dir, pattern = ".+\\.cor$")
  stopifnot(length(cor_file_in) <= 1)
  if (length(cor_file_in) == 1) {
    if (file.exists(file.path(dir, "covar.sso"))) {
      outvec["hess"] <- 1
    }
  }
  return(outvec)
}
