#' Determine if a SS run was successful
#'
#' Use the presence of files generated by SS to determine if the
#' run was successful or not. There are two levels of success that must
#' be determined if the run was meant to include estimating the hessian.
#'
#' @param dir A character string specifying the path to the folder with the
#' results from the run of the SS model.
#'
#' @return A named vector with two values, \code{ran} and \code{hess},
#' (1) a zero or one for the presence of the \code{Report.sso} file and 
#' (2) a zero or one for the presence of a positive definite hessian matrix.
#' @author Kelli Faye Johnson
#'
get_success <- function(dir) {
  outvec <- c("ran" = 0, "hess" = 0)
  if (file.exists(file.path(dir, "Report.sso"))) {
    outvec["ran"] <- 1
  } else {
    return(outvec)
  }
  par_file_in <- dir(dir, pattern = ".+par$")
  cor_file_in <- gsub("par", "cor", par_file_in)
  if (file.exists(file.path(dir, cor_file_in))) {
    outvec["hess"] <- 1
  }
  return(outvec)
}
