on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - '**.md'
  pull_request:
  schedule:
    # This should run the default branch weekly on sunday
    - cron: '0 0 * * 0'
name: call-r-cmd-check
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/r-cmd-check.yml@main
