on:
  workflow_dispatch:
  push:
    branches: [main, master]
    tags: ['*']

name: call-update-pkgdown
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/update-pkgdown.yml@main
